#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#define WORLD_MAP_ID (0)
#define WORLD_DEFAULT_X (540)
#define WORLD_DEFAULT_Y (120)

#define MAP_TILE_BLOCK_ATTR (1)

#define CHARACTER_WIDTH (32)
#define CHARACTER_WIDTH_2 (24)
#define CHARACTER_HEIGHT (36)
#define CHARACTER_SPIN_SPEED (20)
#define CHARACTER_JUMP_PER_PIXEL_TOLERANCE (20)

#define CHARACTER_SPRITE_Z (450)
#define DAMAGE_FX_SPRITE_Z (430)

#define STUN_LIGHT_FRAMES (18)
#define STUN_HEAVY_FRAMES (24)
#define COUNTER_STUN_FRAMES (120)

#endif
